# Rule to build the Java program
java_binary(
    name = "hello_java",
    srcs = ["main.java"],
    main_class = "Main",
)

# Rule to run the Python script
py_binary(
    name = "script",
    srcs = ["script.py"],
    main = "script.py",
)
